### PR TITLE
[caclmgrd]: Tests for IP2ME rules generation

### PR DESCRIPTION
**Pull request by bluecmd**
**Why I did it:**

We want to contribute some improvements to the IP2ME rules generation logic. Before we do that, we suggest adding unit tests for these rules to easier review the new behavior.

The test cases mirror the current behavior.

### CODE REVIEW

**Comment by bluecmd** [comment]
@qiluo-msft Could you assign someone to review this? Thanks!

**Comment by qiluo-msft** [comment]
@prsunny @bingwang-ms Could you help review?

**Review by prsunny — APPROVED** [review]

**Comment by bluecmd** [comment]
Friendly ping @bingwang-ms! :-)

**Comment by zhangyanzhao** [comment]
We hit some technical issue on EasyCLA sign and we are actively working with LF folks to fix it.

**Comment by bluecmd** [comment]
Seems like the EasyCLA check is working now! :partying_face:

**Pull request merged**
