### PR TITLE
[caclmgrd][chassis]: Fix missing acl rules to allow internal docker traffic from fabric namespaces

### PR DESCRIPTION
**Pull request by SuvarnaMeenakshi**
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
Requires https://github.com/sonic-net/sonic-buildimage/pull/11793
test_cacl_application fails on VoQ chassis Supervisor with the error:
Failed: Missing expected iptables rules: set(['-A INPUT -s 240.127.1.1/32 -d 240.127.1.1/32 -j ACCEPT', '-A INPUT -s 240.127.1.3/32 -d 240.127.1.1/32 -j ACCEPT', '-A INPUT -s 240.127.1.2/32 -d 240.127.1.1/32 -j ACCEPT'])
This failure is seen because acl rules to allow traffic from fabric namespaces is missing.
This PR is to include fabric namespace docker mgmt ips so that acl rules to allow traffic from namespace is added for fabric namespace as well.
Initial PR which added support for multi-asic for reference: https://github.com/sonic-net/sonic-buildimage/pull/5022

### CODE REVIEW

**Comment by arlakshm** [comment]
Can you rebase your branch ?

**Review by judyjoseph — APPROVED** [review]
LGTM

**Pull request merged**
