### PR TITLE
Add LDAP feature support

### PR DESCRIPTION
**Pull request by davidpil2002**
Added LDAP support to hostcfgd

LDAP HLD: https://github.com/sonic-net/SONiC/pull/1487 

This PR depends on the following PR: https://github.com/sonic-net/sonic-buildimage/pull/16969

Details:
The fail (in the build check) reason is that this sonic-host-services LDAP unit tests have dependencies of the following PR: https://github.com/sonic-net/sonic-buildimage/pull/16969

once the PR is merged, all the tests will pass

### CODE REVIEW

**Comment by davidpil2002** [comment]
The fail (in the build check) reason is that this sonic-host-services LDAP unit tests have dependencies of the following PR: https://github.com/sonic-net/sonic-buildimage/pull/16969

once the PR is merged, all the tests will pass

**Comment by liat-grozovik** [comment]
@lguohan who should review and provide feedback?

**Comment by Yarden-Z** [comment]
@lguohan / @qiluo-msft - are there any additional comments here?

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
