### PR TITLE
Add remote syslog configuration

### PR DESCRIPTION
**Pull request by iavraham**
Adding the following functionality:

- Configure remote syslog servers: protocol, filter, severity level
- Update global syslog configuration: severity level, message format

### CODE REVIEW

**Comment by iavraham** [comment]
RUN_CI

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@iavraham Can you please restart the pipeline?

**Review by wen587 — APPROVED** [review]
Please fix build issue

**Review by wen587 — APPROVED** [review]
Please fix build issue

**Comment by fastiuk** [comment]
> Please fix build issue

It is not possible until https://github.com/sonic-net/sonic-swss-common/pull/771 will be merged.
It depends on that PR.

**Comment by qiluo-msft** [comment]
sonic-swss-common master build failure:
https://dev.azure.com/mssonic/build/_build?definitionId=9&_a=summary&view=branches
So this PR build does not download the latest artifacts.

**Comment by fastiuk** [comment]
> So this PR build does not download the latest artifacts.
> @liuh-80 is checking on that front.

Nice, thanks

**Comment by liuh-80** [comment]
> > So this PR build does not download the latest artifacts.
> > @liuh-80 is checking on that front.
> 
> Nice, thanks

The issue caused by a UT timeout, I create PR to mitigate this issue: https://github.com/sonic-net/sonic-swss-common/pull/786

**Comment by liuh-80** [comment]
@fastiuk . the issue fixed, I trigger validation again and it's passed.

**Pull request merged**
