### PR TITLE
Check SONiC dependencies before installation.

### PR DESCRIPTION
**Pull request by liushilongbuaa**
Why I did it
SONiC related packages shouldn't be intalled from Pypi.
It is security compliance requirement.

How I did it
Check SONiC related packages when using setup.py.

### CODE REVIEW

**Review by xumia — APPROVED** [review]

**Comment by xumia** [comment]
LGTM, @qiluo-msft , do you think it is good?

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This file is only used in build time or unit test, not in runtime. We can safely override the coverage checker.

**Pull request merged**
